# Generated by Django 4.1.3 on 2022-11-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.AddField(
            model_name='product',
            name='img_1',
            field=models.ImageField(default=True, upload_to='photos/products'),
        ),
        migrations.AddField(
            model_name='product',
            name='img_2',
            field=models.ImageField(null=True, upload_to='photos/products'),
        ),
    ]
