# Generated by Django 4.1.3 on 2022-11-29 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_img_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='img_1',
            new_name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='product',
            name='img_2',
        ),
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='phtots/products')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
