# Generated by Django 4.1.3 on 2022-11-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_img_1_product_thumbnail_remove_product_img_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(upload_to='photos/products'),
        ),
    ]
