# Generated by Django 4.1.3 on 2022-11-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail_2',
            field=models.ImageField(blank=True, null=True, upload_to='photos/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(default=True, upload_to='photos/products'),
        ),
    ]
