# Generated by Django 4.1.3 on 2022-12-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_image_alter_product_price_delete_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=True, null=True),
        ),
    ]
