# Generated by Django 4.1.3 on 2022-11-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_img_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img_2',
            field=models.ImageField(blank=True, default=True, upload_to='photos/products'),
            preserve_default=False,
        ),
    ]
